### ISSUE TITLE
Request to Enable Docker Support for whyred Kernel

### ISSUE THREAD

**Issue by B-22** [user-why-red/san_kernel_releases#2]
Hello,

I would like to request the addition of Docker support in the kernel for the whyred device. Docker provides a convenient way to run applications in isolated environments, which is very cool and interesting.

**Reference**:
For implementation guidance,  [Docker on Android](https://gist.github.com/FreddieOliveira/efe850df7ff3951cb62d74bd770dce27).

Regardless of whether this feature can be added, I sincerely appreciate your consideration and efforts.

Thank you!

Best regards,

**Comment by user-why-red** [comment]
Your suggestion on adding Docker support in android is cool but Docker relies on specific kernel features primarily designed for server and desktop environments, which are not typically included in Android kernels due to compatibility and performance considerations. This will create additional overhead which is not utilized by every userspace. As such, adding full Docker support to an Android kernel is not practical.

However, for container-like functionality on Android, you might want to explore alternatives such as Termux, Andronix, UserLAnd, or Linux Deploy, which provide a way to run Linux distributions and container-like environments on Android devices
